/**
 * This file was generated by flotiq-api-typegen command
 * Generated at: 2026-03-24T22:09:14.478Z
 */

import {
  DataLink,
  ApiRequest,
  BaseObject,
  SearchParams,
  HydratedSearchResponse,
  InternalGeneratedFormsBase,
  InternalGeneratedForms,
  InternalGeneratedFormsHydrated,
  InternalGeneratedFormsHydratedTwice,
  InternalMediaBase,
  InternalMedia,
  InternalMediaHydrated,
  InternalMediaHydratedTwice,
  InternalPluginSettingsBase,
  InternalPluginSettings,
  InternalPluginSettingsHydrated,
  InternalPluginSettingsHydratedTwice,
  InternalTagBase,
  InternalTag,
  InternalTagHydrated,
  InternalTagHydratedTwice,
  InternalWebhooksBase,
  InternalWebhooks,
  InternalWebhooksHydrated,
  InternalWebhooksHydratedTwice,
} from "@flotiq/flotiq-api-sdk";

type StringWithAutocomplete<T> = T | (string & Record<never, never>);

declare module "@flotiq/flotiq-api-sdk" {
  export type AnySpaceCTD =
    | Product
    | InternalGeneratedForms
    | InternalMedia
    | InternalPluginSettings
    | InternalTag
    | InternalWebhooks;

  export type AnySpaceCTDHydrated =
    | ProductHydrated
    | InternalGeneratedFormsHydrated
    | InternalMediaHydrated
    | InternalPluginSettingsHydrated
    | InternalTagHydrated
    | InternalWebhooksHydrated;

  export type AnySpaceCTDHydratedTwice =
    | ProductHydratedTwice
    | InternalGeneratedFormsHydratedTwice
    | InternalMediaHydratedTwice
    | InternalPluginSettingsHydratedTwice
    | InternalTagHydratedTwice
    | InternalWebhooksHydratedTwice;

  export type AnySpaceCTDBase =
    | ProductBase
    | InternalGeneratedFormsBase
    | InternalMediaBase
    | InternalPluginSettingsBase
    | InternalTagBase
    | InternalWebhooksBase;

  // #region product

  export interface ProductBase extends BaseObject<"product"> {
    name?: string;
    price: Array<Product.PriceBase>;
  }

  export interface Product extends ProductBase {
    price: Array<Product.Price>;
  }

  export interface ProductHydrated extends ProductBase {
    price: Array<Product.PriceHydrated>;
  }

  export interface ProductHydratedTwice extends ProductBase {
    price: Array<Product.PriceHydratedTwice>;
  }

  export namespace Product {
    export type FilterableFields = StringWithAutocomplete<
      "name" | "price" | "price[*].USD" | "price[*].EUR" | "price[*].ARS"
    >;

    // #region Product.price

    export interface PriceBase {
      USD: number;
      EUR: number;
      ARS: number;
    }

    export interface Price extends PriceBase {}

    export interface PriceHydrated extends PriceBase {}

    export interface PriceHydratedTwice extends PriceBase {}

    export namespace Price {
      export type FilterableFields = StringWithAutocomplete<
        "USD" | "EUR" | "ARS"
      >;
    }

    // #endregion
  }

  // #endregion

  export interface FlotiqObjectAPI {
    product: ApiRequest<
      Product,
      ProductHydrated,
      ProductHydratedTwice,
      Product.FilterableFields
    >;

    _generated_forms: ApiRequest<
      InternalGeneratedForms,
      InternalGeneratedFormsHydrated,
      InternalGeneratedFormsHydratedTwice,
      InternalGeneratedForms.FilterableFields
    >;

    _media: ApiRequest<
      InternalMedia,
      InternalMediaHydrated,
      InternalMediaHydratedTwice,
      InternalMedia.FilterableFields
    >;

    _plugin_settings: ApiRequest<
      InternalPluginSettings,
      InternalPluginSettingsHydrated,
      InternalPluginSettingsHydratedTwice,
      InternalPluginSettings.FilterableFields
    >;

    _tag: ApiRequest<
      InternalTag,
      InternalTagHydrated,
      InternalTagHydratedTwice,
      InternalTag.FilterableFields
    >;

    _webhooks: ApiRequest<
      InternalWebhooks,
      InternalWebhooksHydrated,
      InternalWebhooksHydratedTwice,
      InternalWebhooks.FilterableFields
    >;
  }

  export interface FlotiqSearchAPI {
    query<P extends SearchParams>(
      params?: P,
    ): Promise<
      HydratedSearchResponse<
        P,
        AnySpaceCTD,
        AnySpaceCTDHydrated,
        AnySpaceCTDHydratedTwice
      >
    >;
  }
}
